server:
    listen: :53
    upstreams:
        - 192.168.86.1:53
        - 1.1.1.1:53
        - 8.8.8.8:53
    default_profile: default
profiles:
    - name: ari
      block:
        - '**.cai.app'
        - '**.cai.cloud'
        - '**.cai.dev'
        - '**.cai.network'
        - '**.cai.run'
        - '**.cai.space'
        - '**.cai.systems'
        - '**.cai.tools'
        - '**.character.ai'
        - '**.facebook.com'
        - '**.instagram.com'
        - '**.onlyfans.com'
        - '**.pornhub.com'
        - '**.reddit.com'
        - '**.snapchat.com'
        - '**.tiktok.com'
        - '**.twitter.com'
        - '**.x.com'
        - '**.youtube.com'
        - '**character.ai.lan'
      allow_only: []
    - name: block-ads
      block:
        - '**.adnxs.com'
        - '**.adroll.com'
        - '**.adsafeprotected.com'
        - '**.adservice.google.com'
        - '**.advertising.com'
        - '**.adzerk.net'
        - '**.amazon-adsystem.com'
        - '**.appnexus.com'
        - '**.criteo.com'
        - '**.doubleclick.net'
        - '**.doubleverify.com'
        - '**.facebook.com/ads'
        - '**.g.doubleclick.net'
        - '**.googleadservices.com'
        - '**.googlesyndication.com'
        - '**.outbrain.com'
        - '**.pubmatic.com'
        - '**.rubiconproject.com'
        - '**.taboola.com'
      allow_only: []
    - name: default
      block: []
      allow_only: []
    - name: iot
      block: []
      allow_only:
        - '**.amazonaws.com'
        - '**.apple.com'
        - '**.googleapis.com'
        - '**.ntp.org'
        - ntp.org
        - pool.ntp.org
    - name: kids
      block:
        - '**.facebook.com'
        - '**.instagram.com'
        - '**.onlyfans.com'
        - '**.pornhub.com'
        - '**.reddit.com'
        - '**.snapchat.com'
        - '**.tiktok.com'
        - '**.twitter.com'
        - '**.x.com'
        - '**.youtube.com'
      allow_only: []
    - name: night-block
      block: []
      allow_only:
        - '**.apple.com'
    - name: test
      block: []
      allow_only:
        - '**.apple.com'
devices:
    - mac: 14:7d:da:4f:3e:18
      name: ari-laptop
      profile: ""
    - mac: be:ba:5d:6d:55:99
      name: dads-phone
      profile: ""
device_groups:
    - name: ari
      profile: ari
      devices:
        - 14:7d:da:4f:3e:18
      schedules:
        - profile: night-block
          start: "23:00"
          end: "06:30"
    - name: dad
      profile: default
      devices:
        - be:ba:5d:6d:55:99
